<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        jQuery('#generate_random').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onSuccess: function(response) {
					//console.log(response);
					console.log(response.responseJSON.hash);
					jQuery('#payment_us_btcz_secret_key').val(response.responseJSON.hash);
                    if (response.status > 200) {
                    }
                    
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
